version: '3'
services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
       - client:/optimg/client/build
       - ${IMAGE_PATH}:/mnt/images
    environment:
        - IMAGE_PATH=/mnt/images # here it is
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - client:/var/www/client
volumes:
  client:

